### ISSUE TITLE
'Wiki' link now behind ETH login

### ISSUE THREAD

**Issue by mccabete** [holukas/dyco#1]
The "[Wiki](https://gitlab.ethz.ch/holukas/dyco-dynamic-lag-compensation/-/wikis/home)" link is now behind an ETH login. 

When the account was hosted by ETH I was able to access the Wiki and the documentation and the installation instructions, so I know they are there, but now I can't. Hopefully the link just can be updated? 

Once the wiki content is available again, I would consider the **Installation instructions** and  most of **Example Usage** check marks complete.

**Comment by holukas** [comment]
I re-activated the Wiki here: [DYCO Wiki ](https://github.com/holukas/dyco/wiki/DYCO-Wiki). The original Wiki was lost during the migration from GitLab to GitHub. I expanded the Wiki a little bit: it gives a more detailed [usage example](https://github.com/holukas/dyco/wiki/Example), a better overview of the [processing chain](https://github.com/holukas/dyco/wiki/Processing-Chain)  and an [overview of the output folders ](https://github.com/holukas/dyco/wiki/Results-Output-Folders)that are generated during processing.
