### ISSUE TITLE
Command-line usage

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#10]
The description [here](https://github.com/holukas/dyco/wiki/Processing-Chain) indicates that DYCO creates a number of folders and output files.

I think this isn't really appropriate for a tool that's expected to be used within Python. If this is a library, it's outputs should be variables that can be used programmatically. If this isn't a library, then there should be a command-line way to interact with the script.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
I agree and adjusted the code so it can be controlled from the command-line (afd19023c21ec49566d2fde5518a54d4e5c22f91).

**Comment by r-barnes** [comment]
Hey, if I don't mention it elsewhere, nice use of type annotations (at least in some places)!
