### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#16]
Please make sure there is no dead code. Either put code in a switch or remove it. Don't leave large sections commented-out. One example of the issue is [here](https://github.com/holukas/dyco/blob/main/dyco/analyze.py#L354-L377); there are others.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
Removed dead code in d16db2df4ae43a0458e370f9bc61f7b32f29a097

**Comment by r-barnes** [comment]
I'm still seeing a bit of this in tests/test_dyco.py

I won't hold up the review any further on it, but could you check into the situation? It's ~5 LOC.

**Comment by holukas** [comment]
Yes there is some more, I must have missed it. I removed the dead code in 9bd00c6e0c6949c04a62c2a5ba71ca47c4b4a588.
