### ISSUE TITLE
Method/Function Documentation

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#17]
There are a number of methods and functions without documentation in, e.g., these files:
https://github.com/holukas/dyco/blob/main/dyco/analyze.py
https://github.com/holukas/dyco/blob/main/dyco/plot.py
https://github.com/holukas/dyco/blob/main/dyco/files.py

Please make sure that all public methods/functions are appropriately documented.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
Thanks for pointing this out, I added additional documentation in a27f527b6e10f8ffd8a0744554bbd74e76da80e5.

**Comment by r-barnes** [comment]
pylint still shows some undocumented functions/classes:

dyco/setup_dyco.py:97:0: C0115: Missing class docstring (missing-class-docstring)
dyco/setup_dyco.py:104:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/setup_dyco.py:195:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/dyco.py:52:4: C0115: Missing class docstring (missing-class-docstring)
dyco/dyco.py:467:0: C0116: Missing function or method docstring (missing-function-docstring)
dyco/plot.py:32:0: C0115: Missing class docstring (missing-class-docstring)
dyco/plot.py:44:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/plot.py:124:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/plot.py:169:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/plot.py:258:0: C0116: Missing function or method docstring (missing-function-docstring)
dyco/plot.py:284:0: C0116: Missing function or method docstring (missing-function-docstring)
dyco/loop.py:304:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/loop.py:583:0: C0115: Missing class docstring (missing-class-docstring)
dyco/lag.py:220:4: C0116: Missing function or method docstring (missing-function-docstring)
dyco/lag.py:515:0: C0115: Missing class docstring (missing-class-docstring)
dyco/lag.py:569:4: C0116: Missing function or method docstring (missing-function-docstring)

**Comment by holukas** [comment]
I added the missing docstrings in 0ff3f62627e40181df2c6d589ff2f8786d6596de. I hope I did not miss anything.
