### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#18]
A few notes on the Example.

> 20161024100000.csv 20161024110000.csv 20161024120000.csv 20161024130000.csv 20161024140000.csv
20161024103000.csv 20161024113000.csv 20161024123000.csv 20161024133000.csv 20161024143000.csv

Please clarify that those files are available in example/input_data

**Comment by holukas** [comment]
I added a short line about the data availability in the Wiki/Example:

"--> The 10 example files are available for download here: [example/input_data](https://github.com/holukas/dyco/tree/main/example/input_data)."
