### ISSUE TITLE
Friendlier wiki

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#6]
The link to the wiki from the README drops onto a page from which it's not obvious where the user should go. I think it would be better if the README dropped the user onto a friendly landing page in the wiki from which it would be clear where to start.

In particular the page named "DYCO Wiki" appears to just duplicate the existing landing page.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
I removed the duplicate and tried to make the welcome page a bit nicer. In addition, all texts in the wiki were updated and more plots showing DYCO results were added.

https://github.com/holukas/dyco/wiki

**Comment by r-barnes** [comment]
This is much better, thanks.
