### ISSUE TITLE
"Example settings"

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#7]
On https://github.com/holukas/dyco/wiki/Example it's unclear that I'm supposed to click the "Example Settings" link to view the code being discussed. It would be better to either embed a copy of the code in the page or at least highlight that the user should open the link for cross-referencing.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
I restructured and reworded the [Example](https://github.com/holukas/dyco/wiki/Example) and tried to include more information about how the script is used. I also added an example for the command line interface with full arguments and added separate wiki pages for [Usage](https://github.com/holukas/dyco/wiki/Usage) and [Results Output Folders](https://github.com/holukas/dyco/wiki/Results-Output-Folders).

**Comment by r-barnes** [comment]
Okay, thanks!
