### ISSUE TITLE
Pathlib

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#8]
I see this 
> At the moment it is also necessary to include the import from pathlib import Path.
in https://github.com/holukas/dyco/wiki/Example

Why is this so? Can it be fixed?

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
After some thinking and then some more trial-and-error, I was able to remove the pathlib requirement in afd19023c21ec49566d2fde5518a54d4e5c22f91.
