### ISSUE TITLE
Inputs/outputs

### ISSUE THREAD

**Issue by r-barnes** [holukas/dyco#9]
I feel like it's a little unclear to me from the README what the inputs and outputs of the software are.

Is it possible to summarize very briefly what it does? I feel like there's currently a wall-of-text issue.

openjournals/joss-reviews/issues/2575

**Comment by holukas** [comment]
I tried to clarify this point and adjusted the texts in the paper and the README (69a7ccb115e172e344aa8f92693273b4d4674c9d).

- The texts now mention eddy covariance raw data files specifically as input files:
> `DYCO` uses eddy covariance raw data files as input and produces lag-compensated raw data files as output.
- The `DYCO` [processing chain flowchart ](https://github.com/holukas/dyco/blob/main/paper/dyco_processing_chain.png)now mentions eddy covariance data files specifically as input.
